[package]
name = "project_euler"
description = "Project Euler solutions in Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[profile.test]
opt-level = 3

[dependencies]
clap = { version = "4.4.4", features = ["cargo"] }
# itertools = "0.11.0"
